In [1]:
import pandas as pd
from glob import glob

In [2]:
export_folder = "/home/hv270/rds/rds-who1000-cbrc/user/wja24/shared/hippolyte_only/interval_processing"
EUR_path_interval = "%s/genetic_score/EUR_interval" % export_folder
EUR_path = "%s/genetic_score/EUR" % export_folder
#tag = "26_nov" one after NY, without age and sex covariates
tag = "20_dec_21"

In [3]:
chr_group_files = glob("%s/%s/bolt_res_bgen_feb_ADP_pred_chr*" % (export_folder,tag))

In [4]:
bgs = []
for f in chr_group_files:
    df = pd.read_csv(f,sep="\t")
    assert df.isnull().sum(axis=0).sum() == 0
    bgs.append(df)
bg = pd.concat(bgs,axis=0).sort_values(["CHR","BP"])

In [18]:
litterature_IDs = [
    "rs12566888",
    "rs2363910",
    "rs7940646",
    "rs12566888",
    "rs431194",
    "rs10761741",
    "rs1671152",
    "rs12041331",
    "rs12041331",
    "rs12041331",
    "rs11924165",
    "rs10883735",
    "rs11202221",
    "rs6566765",
    "rs9889955",
    "rs10886430",
    "rs12566888",
    "rs7624918",
    "rs1613662",
    "rs773902",
    "rs10886430",
    "rs12137738",
    "rs142001088",
    "rs12041331",
    "rs12041331",
    "rs12041331",
    "rs1175170",
    "rs112157462",
    "rs58250884",
    "rs185159562",
    "rs138028657",
    "rs7097060",
    "rs183146849",
    "rs140148392",
    "rs61974290",
    "rs575524466",
    "rs1207486385",
    "rs1207486385",
    "rs138845468",
    "rs542707094",
    "rs61751937",
    "rs143238312",
    "rs150291014",
    "rs763817905",
    "rs61752770"]
litterature_IDs = list(set(litterature_IDs))

In [20]:
len(litterature_IDs)

36

In [21]:
bg.head()

,SNP,CHR,BP,GENPOS,ALLELE1,ALLELE0,A1FREQ,INFO,CHISQ_LINREG,P_LINREG,BETA,SE,CHISQ_BOLT_LMM_INF,P_BOLT_LMM_INF,CHISQ_BOLT_LMM,P_BOLT_LMM
591379,rs367896724,1,10177,0,A,AC,0.623991,0.735090,0.267213,0.61,0.003642,0.008563,0.180860,0.67,0.208059,0.65
591380,rs145072688,1,10352,0,T,TA,0.622860,0.722254,0.759546,0.38,-0.007107,0.008604,0.682318,0.41,0.614900,0.43
591381,rs575272151,1,11008,0,C,G,0.915802,0.737639,0.654907,0.42,0.010514,0.014847,0.501494,0.48,0.647073,0.42
591382,rs544419019,1,11012,0,C,G,0.918340,0.730055,0.031515,0.86,0.000202,0.015148,0.000178,0.99,0.001427,0.97
591383,rs540538026,1,13110,0,G,A,0.942219,0.686493,0.007756,0.93,0.001711,0.018347,0.008700,0.93,0.002563,0.96

In [22]:
sub_bg = bg.loc[bg.SNP.isin(litterature_IDs)]

In [14]:
bg.loc[bg.SNP == "rs869244"]

,SNP,CHR,BP,GENPOS,ALLELE1,ALLELE0,A1FREQ,INFO,CHISQ_LINREG,P_LINREG,BETA,SE,CHISQ_BOLT_LMM_INF,P_BOLT_LMM_INF,CHISQ_BOLT_LMM,P_BOLT_LMM
1131093,rs869244,10,112909105,0,G,A,0.635485,0.98533,0.744335,0.39,0.00731,0.007447,0.963643,0.33,0.809259,0.37

In [63]:
sub_bg["A0FREQ"] = 1.-sub_bg["A1FREQ"]
sub_bg["MAF"] = sub_bg[["A1FREQ","A0FREQ"]].min(axis=1)

/home/hv270/platelets/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/home/hv270/platelets/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [64]:
sub_bg[["SNP","P_BOLT_LMM","MAF"]]

                 SNP    P_BOLT_LMM       MAF
670944    rs12137738  2.700000e-01  0.101894
817533   rs142001088  7.600000e-01  0.022221
1028156   rs12566888  1.200000e-24  0.091408
1028160   rs12041331  8.800000e-24  0.090485
1154627    rs1175170  1.900000e-01  0.481623
937552     rs7624918  8.600000e-08  0.354346
1303719  rs112157462  1.600000e-01  0.031318
2239542   rs58250884  8.800000e-01  0.049708
574720     rs2363910  3.800000e-01  0.089383
1165626   rs61751937  5.000000e-16  0.029654
961447    rs10761741  7.200000e-01  0.420633
1005751  rs138028657  1.300000e-01  0.014107
1050651   rs11202221  6.400000e-01  0.194021
1101806   rs10883735  9.500000e-01  0.078370
1131055    rs7097060  9.400000e-01  0.160636
1158148   rs10886430  3.300000e-10  0.138942
50157      rs7940646  4.100000e-05  0.304999
333529   rs183146849  1.400000e-02  0.019893
1744151  rs140148392  9.400000e-01  0.012265
1728336   rs61974290  8.600000e-01  0.078461
805555   rs143238312  9.800000e-01  0.011174
2030886    rs9889955  5.400000e-01  0.176578
90386    rs138845468  6.100000e-02  0.097191
253934     rs6566765  6.200000e-01  0.350803
359077      rs773902  5.700000e-02  0.189545
509662     rs1671152  2.300000e-19  0.161431
509728     rs1613662  3.300000e-22  0.167440

In [60]:
sub_bg.loc[(sub_bg.P_BOLT_LMM < 1e-3) & (sub_bg.P_BOLT_LMM > 1e-8)]

,SNP,CHR,BP,GENPOS,ALLELE1,ALLELE0,A1FREQ,INFO,CHISQ_LINREG,P_LINREG,BETA,SE,CHISQ_BOLT_LMM_INF,P_BOLT_LMM_INF,CHISQ_BOLT_LMM,P_BOLT_LMM
937552,rs7624918,3,56901292,0,C,T,0.645654,0.921186,26.2361,3.000000e-07,-0.040886,0.007759,27.7701,1.400000e-07,28.6579,8.600000e-08
50157,rs7940646,11,10669228,0,T,C,0.304999,0.998587,16.4639,5.000000e-05,0.032097,0.007740,17.1955,3.400000e-05,16.8263,4.100000e-05

In [24]:
missing = [s for s in litterature_IDs if s not in sub_bg.SNP.unique().tolist()]

In [80]:
bg["MBP"] = bg["BP"] // int(1e6)

In [84]:
bg.loc[bg.CHR == 17].sort_values("P_BOLT_LMM").groupby("MBP").first().sort_values("P_BOLT_LMM").head(20)

,SNP,CHR,BP,GENPOS,ALLELE1,ALLELE0,A1FREQ,INFO,CHISQ_LINREG,P_LINREG,BETA,SE,CHISQ_BOLT_LMM_INF,P_BOLT_LMM_INF,CHISQ_BOLT_LMM,P_BOLT_LMM
MBP,,,,,,,,,,,,,,,,
3,rs11078475,17,3819002,0,T,C,0.471196,0.988704,38.5330,5.400000e-10,-0.045222,0.007147,40.0396,2.500000e-10,40.7550,1.700000e-10
78,rs2245187,17,78827124,0,T,C,0.106669,0.956499,19.9823,7.800000e-06,0.054493,0.011756,21.4851,3.600000e-06,20.7833,5.100000e-06
73,rs11870078,17,73838108,0,G,A,0.764690,0.993837,17.5594,2.800000e-05,-0.035396,0.008357,17.9404,2.300000e-05,18.2745,1.900000e-05
35,rs72826135,17,35293520,0,G,A,0.928224,0.966379,17.9851,2.200000e-05,-0.059792,0.013973,18.3117,1.900000e-05,18.1554,2.000000e-05
61,rs372663622,17,61636696,0,A,G,0.749385,0.975827,15.7314,7.300000e-05,0.033667,0.008241,16.6890,4.400000e-05,17.4451,3.000000e-05
51,rs806930,17,51370626,0,A,C,0.116959,0.976846,16.9994,3.700000e-05,-0.046564,0.011133,17.4937,2.900000e-05,16.7384,4.300000e-05
4,rs427703,17,4893357,0,G,C,0.274736,0.994489,16.9038,3.900000e-05,-0.032624,0.008001,16.6241,4.600000e-05,16.6809,4.400000e-05
10,rs112691244,17,10777747,0,A,G,0.662696,0.890685,16.1877,5.700000e-05,0.031015,0.007958,15.1884,9.700000e-05,15.8282,6.900000e-05
72,rs11077725,17,72106312,0,C,T,0.839138,0.985327,16.8105,4.100000e-05,-0.038089,0.009732,15.3175,9.100000e-05,15.6888,7.500000e-05
19,rs192706608,17,19201966,0,C,T,0.989179,0.834930,15.8717,6.800000e-05,0.147716,0.037413,15.5885,7.900000e-05,15.5954,7.800000e-05
25,rs139905858,17,25974964,0,C,A,0.987864,0.774427,14.8704,1.200000e-04,-0.142335,0.036984,14.8115,1.200000e-04,15.4492,8.500000e-05
14,rs72820651,17,14277077,0,G,A,0.989337,0.869086,15.2410,9.500000e-05,0.142197,0.036925,14.8298,1.200000e-04,15.4161,8.600000e-05
76,rs9893988,17,76172167,0,G,A,0.740977,0.985739,17.5627,2.800000e-05,-0.032317,0.008174,15.6294,7.700000e-05,15.2643,9.300000e-05
5,rs12453864,17,5674953,0,C,T,0.546171,0.969415,14.3011,1.600000e-04,-0.027666,0.007262,14.5152,1.400000e-04,15.2102,9.600000e-05
30,rs143292291,17,30645493,0,AAC,A,0.851238,0.915670,15.9569,6.500000e-05,-0.041247,0.010408,15.7048,7.400000e-05,15.1643,9.900000e-05
71,rs8076982,17,71115694,0,G,T,0.833228,0.942492,14.5646,1.400000e-04,-0.038159,0.009766,15.2676,9.300000e-05,14.7214,1.200000e-04
28,rs184713097,17,28650768,0,G,A,0.973778,0.835778,14.5251,1.400000e-04,-0.091504,0.024335,14.1389,1.700000e-04,14.6074,1.300000e-04
12,rs7225108,17,12836902,0,A,T,0.765957,0.950324,14.8666,1.200000e-04,0.033100,0.008624,14.7310,1.200000e-04,14.3334,1.500000e-04
70,rs12939126,17,70660427,0,C,T,0.977482,0.851412,14.1069,1.700000e-04,0.098030,0.025811,14.4248,1.500000e-04,14.3727,1.500000e-04
41,rs28548107,17,41744649,0,A,G,0.766604,0.915250,14.9874,1.100000e-04,0.033276,0.008819,14.2384,1.600000e-04,14.2835,1.600000e-04

In [59]:
bg.loc[bg.SNP == "rs543934832"]

Empty DataFrame
Columns: [SNP, CHR, BP, GENPOS, ALLELE1, ALLELE0, A1FREQ, INFO, CHISQ_LINREG, P_LINREG, BETA, SE, CHISQ_BOLT_LMM_INF, P_BOLT_LMM_INF, CHISQ_BOLT_LMM, P_BOLT_LMM]
Index: []

In [70]:
bg.loc[(bg.CHR == 17) & (bg.BP // int(1e6) == 21)].sort_values("P_BOLT_LMM")

,SNP,CHR,BP,GENPOS,ALLELE1,ALLELE0,A1FREQ,INFO,CHISQ_LINREG,P_LINREG,BETA,SE,CHISQ_BOLT_LMM_INF,P_BOLT_LMM_INF,CHISQ_BOLT_LMM,P_BOLT_LMM
1882671,rs117642733,17,21284910,0,C,T,0.946741,0.847979,10.002300,0.0016,0.055780,0.017227,10.484200,0.0012,1.011950e+01,0.0015
1882914,rs1914890,17,21340004,0,G,A,0.582209,0.889616,8.471700,0.0036,0.022796,0.007614,8.964610,0.0028,8.842440e+00,0.0029
1883293,rs529828818,17,21523174,0,C,T,0.972887,0.706140,9.117740,0.0025,-0.077137,0.025699,9.009180,0.0027,8.643650e+00,0.0033
1882674,rs4986049,17,21285926,0,C,A,0.716598,0.650008,7.819330,0.0052,-0.027210,0.009727,7.825870,0.0052,7.714240e+00,0.0055
1882903,rs55807346,17,21338047,0,A,G,0.569550,0.862675,7.331700,0.0068,0.021518,0.007704,7.801350,0.0052,7.595340e+00,0.0059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1882974,rs181967189,17,21365202,0,T,C,0.988733,0.685670,0.001559,0.9700,0.002767,0.040596,0.004646,0.9500,2.238960e-05,1.0000
1883778,rs11871441,17,21799482,0,C,T,0.990004,0.796249,0.062773,0.8000,0.006877,0.039911,0.029694,0.8600,1.199140e-07,1.0000
1884388,rs1518051,17,21985976,0,G,A,0.978481,0.986315,0.017819,0.8900,-0.002664,0.024629,0.011697,0.9100,1.580540e-05,1.0000
1882424,rs114473529,17,21194771,0,A,T,0.593373,0.509223,0.020678,0.8900,0.001083,0.010130,0.011421,0.9100,4.013650e-07,1.0000
1883707,rs28891727,17,21756866,0,G,A,0.250376,0.910115,0.000199,0.9900,-0.000461,0.008595,0.002875,0.9600,3.715150e-05,1.0000