In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/bolt_res_ADP_FIB", sep="\t")

In [3]:
df.head()

,SNP,CHR,BP,GENPOS,ALLELE1,ALLELE0,A1FREQ,F_MISS,BETA,SE,P_BOLT_LMM_INF,P_BOLT_LMM
0,rs568149713,1,15777,0,A,G,0.991720,0.037848,0.028324,0.029405,0.34,0.38
1,rs199745162,1,16949,0,A,C,0.986555,0.048640,-0.012154,0.023406,0.60,0.64
2,rs533090414,1,18849,0,C,G,0.022743,0.050293,-0.010023,0.018055,0.58,0.59
3,rs2691277,1,52238,0,T,G,0.012450,0.051075,-0.019972,0.024132,0.41,0.40
4,rs552304420,1,54712,0,T,C,0.993437,0.022035,0.009477,0.032930,0.77,0.80

In [5]:
df["MBP"] = (df["BP"] / int(1e6)).astype(int)

In [9]:
df.loc[df.P_BOLT_LMM <5e-8].sort_values(by="P_BOLT_LMM", ascending=True).groupby(["CHR","MBP"])[["P_BOLT_LMM","SNP"]].first()

           P_BOLT_LMM          SNP
CHR MBP
1   113  7.900000e-10   rs10776757
    156  1.800000e-08   rs72698679
    171  2.600000e-12    rs6425521
    198  7.500000e-24   rs10919615
    199  1.300000e-25    rs1434282
    207  2.300000e-31   rs34101855
2   31   3.700000e-09    rs3769631
3   111  7.000000e-09    rs1355767
4   6    2.500000e-09   rs11731274
5   122  1.600000e-28     rs152039
    150  2.500000e-11   rs56859579
6   25   3.300000e-15   rs57318254
    137  3.900000e-19   rs12191772
    158  2.900000e-09     rs688181
7   106  1.700000e-19     rs342293
    116  4.100000e-08   rs13239000
8   106  5.800000e-29    rs6993770
    144  8.400000e-09   rs55836855
    145  1.100000e-10   rs11136339
9   113  2.000000e-10   rs61751937
    135  4.000000e-08   rs61469632
10  64   2.600000e-12   rs35562567
    65   1.800000e-13   rs10822155
12  54   6.100000e-09    rs6580981
15  65   2.300000e-23    rs1684037
16  9    1.900000e-08    rs9939495
    28   2.400000e-10     rs151233
    81   9.800000e-18   rs74029252
17  4    2.600000e-14  rs200271866
18  9    9.200000e-10   rs11315757
19  16   2.300000e-08    rs8104011
    38   9.300000e-20   rs35496032
    55   7.100000e-21    rs1654425